version: "3"

networks:
  needys-api-strategy:

services:
  needys-api-strategy:
    container_name: needys-api-strategy
    build:
      context: ../
      dockerfile: build/package/Dockerfile.development
    environment:
      ENVIRONMENT: ${NEEDYS_API_STRATEGY_ENVIRONMENT:-development}
      VERBOSITY: ${NEEDYS_API_STRATEGY_VERBOSITY:-debug}
      LOG_FORMAT: ${NEEDYS_API_STRATEGY_LOG_FORMAT:-text}
      LOG_HEALTHCHECK: ${NEEDYS_API_STRATEGY_LOG_FORMAT:-false}
      OPTIONAL_FLAGS: ${NEEDYS_API_STRATEGY_OPTIONAL_FLAGS:-}
    ports:
      - 8011:8011
    volumes:
      - ./../:/application
    networks:
      - needys-api-strategy
    healthcheck:
      test: curl --fail http://localhost:8011/ready || exit 1
      interval: 3s
      timeout: 3s
      retries: 10
